version: 0.2

phases:
  install:
    commands:
      - npm install -g npm
      - npm ci
  pre_build:
    commands:
      - apt install zip
  build:
    commands:
      - npm run build
      - ls dist/websitePractise
      - zip -r buildasset.zip dist/websitePractise/

artifacts:
  files:
    - '**/*'
  base-directory: dist/websitePractise