version: 0.2

phases:
  install:
    commands:
      - npm install -g npm
      - npm ci
  pre_build:
    commands:
      - yum install zip
  build:
    commands:
      - npm run build
      - dir dist/websitePractise
      - zip -r buildasset.zip dist/websitePractise/

artifacts:
  files:
    - '*.zip'