version: 0.2

phases:
  install:
    commands:
      - npm install -g npm
      - npm ci
  build:
    commands:
      - npm run build
      - dir dist/websitePractise

artifacts:
  files:
    - '**/*'
  base-directory: dist/websitePractise